language: generic 
sudo: required #super user permission 
services:
  - docker 

before_install:
  - docker build -t navnathd/docker-react -f Dockerfile.dev . # we can use any tag

  script:
  - docker run -e CI=true navnathd/docker-react npm run test
  